// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        (unknown)
// source: stat.proto

package pb

type Stat struct {
	Fqdn        string `protobuf:"bytes,1,opt,name=fqdn,proto3" json:"fqdn"`
	Count       int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	Image       string `protobuf:"bytes,5,opt,name=image,proto3" json:"image"`
	Lang        string `protobuf:"bytes,6,opt,name=lang,proto3" json:"lang"`
}
