// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        (unknown)
// source: user.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

type User struct {
	Id        uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Uid       string               `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid"`
	Name      string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
}
