# for test
[mysql]
  dbname  = "ogp_test"
  host    = "localhost"
  port    = 5556
  user    = "root"
  pass    = "pass"
  sslmode = "false"
  no-auto-timestamps = "true"

# for local dev
#[mysql]
#  dbname  = "ogp_local"
#  host    = "127.0.0.1"
#  port    = 5555
#  user    = "root"
#  pass    = "pass"
#  sslmode = "false"
#  no-auto-timestamps = "true"
