CREATE TABLE user
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  is_editor BOOLEAN NOT NULL DEFAULT TRUE, # プロトタイプのためデフォルトで誰でも登録可能
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  uid VARCHAR(128) CHARACTER SET ascii UNIQUE NOT NULL,
  username VARCHAR(10) CHARACTER SET ascii UNIQUE NOT NULL,
  displayname VARCHAR(15) CHARACTER SET utf8mb4 NOT NULL,
  avatar VARCHAR(255) CHARACTER SET ascii NOT NULL DEFAULT '',
  provider VARCHAR(20) CHARACTER SET ascii NOT NULL DEFAULT '',
    PRIMARY KEY (id),
    INDEX (username)
)
