name: Staging
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decrypt Secrets
        run: ./server/secrets/decrypt.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GAE_DEPLOY_EMAIL_STG }}
          service_account_key: ${{ secrets.GAE_DEPLOY_KEY_STG }}
      - run: gcloud info

      - name: GAE deploy
        run: |
          cd ./server && gcloud app deploy api.yaml --project $PROJECT_ID --quiet
        env:
          PROJECT_ID: ogp-stg
